BEGIN TRANSACTION;

CREATE TABLE "__DbHistory" (
    "Id" TEXT COLLATE NOCASE NOT NULL CONSTRAINT "PK___DbHistory" PRIMARY KEY
);

CREATE TABLE "EmailAddress" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_EmailAddress" PRIMARY KEY AUTOINCREMENT,
    "UserId" TEXT NOT NULL,
    "Address" TEXT COLLATE NOCASE NULL,
    "AddressType" INTEGER NOT NULL,
    "ForwardAddress" TEXT COLLATE NOCASE NULL
);

CREATE TABLE "Folder" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Folder" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT COLLATE NOCASE NULL,
    "Subscribed" INTEGER NOT NULL
);

CREATE TABLE "Message" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Message" PRIMARY KEY AUTOINCREMENT,
    "SmtpMessageId" TEXT COLLATE NOCASE NULL,
    "UserId" TEXT NOT NULL,
    "AddressId" INTEGER NOT NULL,
    "OutGoing" INTEGER NOT NULL,
    "FolderId" INTEGER NOT NULL,
    "MailFrom" TEXT COLLATE NOCASE NULL,
    "RcptTo" TEXT COLLATE NOCASE NULL,
    "From" TEXT COLLATE NOCASE NULL,
    "To" TEXT COLLATE NOCASE NULL,
    "Cc" TEXT COLLATE NOCASE NULL,
    "Bcc" TEXT COLLATE NOCASE NULL,
    "Subject" TEXT COLLATE NOCASE NULL,
    "BodyPosition" INTEGER NOT NULL,
    "Summary" TEXT COLLATE NOCASE NULL,
    "Size" INTEGER NOT NULL,
    "Read" INTEGER NOT NULL,
    "Answered" INTEGER NOT NULL,
    "Deleted" INTEGER NOT NULL,
    "Flagged" INTEGER NOT NULL,
    "Recent" INTEGER NOT NULL,
    "CreationTime" TEXT NOT NULL,
    "CreationTimeTick" INTEGER NOT NULL,
    "Date" TEXT NOT NULL
);

CREATE TABLE "TargetAddress" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TargetAddress" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT COLLATE NOCASE NULL,
    "Address" TEXT COLLATE NOCASE NULL
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210219065011_Initial', '5.0.0');

COMMIT;


